### ISSUE TITLE
Expecting Service Account when disabled.

### ISSUE THREAD

**Issue by amanhigh** [stakater/application#195]
Default Application doesn't run until Service Account is created.

```
applicationName: "tiny"
deployment:
  image:
    repository: travix/tinyproxy
    tag: latest
```

The above config kept on failing at replica set level. 

Issues making it difficult to use in start.
- No error when deploying, but pods won't come up.
- Not a single example on Homepage which can be copy pasted and run. Eg. (Sample Nginx)
