### ISSUE TITLE
Review the labels and remove the unncessary ones

### ISSUE THREAD

**Issue by rasheedamir** [stakater/application#202]
We should review these labels; as some of them are static and don't make sense

```
  labels:
    app: review
    app.kubernetes.io/instance: gabbar-dev-stakater-nordmart-review
    release: gabbar-dev-stakater-nordmart-review
    provider: stakater
    appVersion: 1.0.43
    team: stakater
    chart: application-1.1.14
    heritage: Helm
    appCategory: backend
    group: com.stakater.platform
```

We can remove these:
- provider: stakater
- team: stakater

And have different names for others
