### ISSUE TITLE
Invalid labels with sha256 digest docker tags

### ISSUE THREAD

**Issue by pauvos** [stakater/application#216]
With docker image tags like...

```yaml
deployment:
  image:
    tag: latest@sha256:f2a9d619483d11cd8b2f12be2bc4fb1cc9b7a4e01295b8ba52d4aea54f528556
```

the chart renders invalid appVersion labels:

```
metadata.labels: Invalid value: \"latest@sha256:f2a9d619483d11cd8b2f12be2bc4fb1cc9b7a4e01295b8ba5\":
a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

Would it be possible to trim everything after "@" or maybe support an optional `applicationVersion` parameter?

I can create a pull request if necessary. Thanks for the great helm chart btw!
