### ISSUE TITLE
service out of sync on argocd on version 2.3.1

### ISSUE THREAD

**Issue by jdcmarques** [stakater/application#294]
**Describe the bug**
Getting consistent Out of Sync on ArgoCD when creating ClusterIP services
![image](https://github.com/stakater/application/assets/8876122/57ff2937-f4ba-4a0e-ba28-86b9564176ba)
Because now `clusterIP` field on spec is always provisioned.
![image](https://github.com/stakater/application/assets/8876122/2431006b-b0d6-45ff-95bc-dd1d1986957a)

Issue was introduced by #275 

**To Reproduce**
```
  service:
    enabled: true
    ports:
      - port: 80
        name: http
        protocol: TCP
        targetPort: http
```
**Expected behavior**
`clusterIP` field is only included when it's specified

**Actual behavior**
`clusterIP` is always included
