### ISSUE TITLE
Is there a way to add support for multiple deployments per application?

### ISSUE THREAD

**Issue by luciano-buono** [stakater/application#374]
**Is your feature request related to a problem? Please describe.**
I need to deploy an app that uses 2 deployments. For now I did a multicontainer deployment but it would be cleaner to be able to specify to separate ones

**Describe the solution you'd like**
deploy an app that uses 2 deployments

**Describe alternatives you've considered**

**Additional context**

**Comment by zioCristia** [comment]
Another workaround to your double container would be to use this chart as a dependency chart and separate it for multiple deployments with an alias.

For example:
```
# Chart.yaml
apiVersion: v2
type: application

name: your-application
description: A Helm chart for multiple deployment of your application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: application
    alias: app1
    version: 6.0.2
    repository: https://stakater.github.io/stakater-charts
  - name: application
    alias: app2
    version: 6.0.2
    repository: https://stakater.github.io/stakater-charts
```

Your values.yaml would be for example:
```
app1:
  applicationName: app1
  deployment:
    image:
      repository: "app1"
      tag: "latest"

app2:
  applicationName: app2
  deployment:
    image:
      repository: "app2"
      tag: "latest"
```

For the duplicate fields you can even use anchors and aliases to reduce duplicates:
```
common:
  namespaceOverride: &namespaceOverride "dev"
  labels: &commonLabels
    group: your.group

app1:
  applicationName: app1
  namespaceOverride: *namespaceOverride
  labels: *commonLabels
  deployment:
    image:
      repository: "app1"
      tag: "latest"

app2:
  applicationName: app2
  namespaceOverride: *namespaceOverride
  labels: *commonLabels
  deployment:
    image:
      repository: "app2"
      tag: "latest"
```
