### ISSUE TITLE
job annotations get rendered as string but require map

### ISSUE THREAD

**Issue by thesephirot** [stakater/application#376]
**Describe the bug**
Job annotations require datatype map but are read as string
**To Reproduce**
configure multiple annotations to be added to the job
```
    jobs:
      jobname:
        annotations:
          argocd.argoproj.io/hook: PostSync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

error message:

`Error: template: backend/charts/application/templates/job.yaml:18:29: executing "backend/charts/application/templates/job.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}`

**Expected behavior**
annotations should be rendered

**Actual behavior**
A clear and concise description of what actually happens.

this could be fixed by changing the job template to:

```
kind: Job
metadata:
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if $job.additionalLabels }}
{{ $job.additionalLabels | indent 4 }}
{{- end }}
{{- with $job.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
```
