### ISSUE TITLE
How to generate externalSecret via helm template?

### ISSUE THREAD

**Issue by minkbear** [stakater/application#379]
my values.yaml as below and run `helm template my-release stakater/application -f values.yaml`

```yaml
service:
  ports: 
    - name: "http"
      port: 3000
      protocol: "TCP"
      targetPort: "http"
deployment:
  replicas: 1
  image:
    repository: test.amazonaws.com/test-apps
    tag: test
  resources:
    limits:
      cpu: 0.5
      memory: 256Mi
    requests:
      cpu: 0.1
      memory: 128Mi
ingress:
  enabled: true
  ingressClassName: "alb"
  hosts:
    - host: test.test.com
      paths:
        - path: /
          pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: p-groups
    alb.ingress.kubernetes.io/success-codes: 200-302
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStore:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  files:
    postgres:
      dataFrom:
        key: /test/postgres/secrets
```

how to fix this?

Thank you.
