### ISSUE TITLE
Optional `envFrom`

### ISSUE THREAD

**Issue by lucasfcnunes** [stakater/application#394]
**Is your feature request related to a problem? Please describe.**
Need the deploy to work even if the referenced `Secret/ConfigMap` on `deployment.envFrom` doesn't exist.

**Describe the solution you'd like**
```yaml
deployment:
  envFrom:
    specific-secrets:
      type: secret
      name: '{{ .Release.Name }}'
      optional: true # <<< NEW!
  env:
    PORT:
      valueFrom:
        configMapKeyRef:
          name: '{{ .Release.Name }}'
          key: PORT
          optional: true # <<< ALREADY WORKS.
```

**Describe alternatives you've considered**
NONE

**Additional context**
NA
